# import base image
FROM ubuntu:bionic

# install system-wide dependencies,
# python3 and the build-time dependencies for c modules
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  python3 python3-dev python3-pip python3-lxml \
  build-essential libffi-dev git locales \
  libtiff5-dev libjpeg8-dev zlib1g-dev libmagic-dev \
  libfreetype6-dev liblcms2-dev libwebp-dev \
  curl libfontconfig nginx \
  libxml2-dev libxslt1-dev \
  python3-venv inotify-tools \
  tzdata \
  && rm /etc/nginx/sites-enabled/default
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y --no-install-recommends \
  nodejs

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV TZ Europe/Berlin



# client ports
EXPOSE 9000
EXPOSE 9200
EXPOSE 80

# server ports
EXPOSE 5000
EXPOSE 5100
EXPOSE 5400

# set env vars for the server
ENV PYTHONUNBUFFERED 1
ENV C_FORCE_ROOT "False"
ENV CELERYBEAT_SCHEDULE_FILENAME /tmp/celerybeatschedule.db

ENV REDIS_URL redis://redis:6379/1
ENV MONGO_URI mongodb://mongodb/test
ENV MONGO_HOST mongodb
ENV ELASTICSEARCH_URL http://elastic:9200
ENV CONTENTAPI_MONGO_URI mongodb://mongodb/superdesk_ca


# test server
COPY ./server /opt/superdesk
WORKDIR /opt/superdesk
RUN python3 -m pip install --upgrade pip setuptools wheel
RUN python3 -m pip install -U -r dev-requirements.txt
CMD python3 -m venv env && . env/bin/activate && nosetests


