apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elasticsearchSuperdesk.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.elasticsearchSuperdesk.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.elasticsearchSuperdesk.component }}
      annotations:
        backup.velero.io/backup-volumes: {{ .Values.elasticsearchSuperdesk.volumeName }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - lb
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - storage
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - database
      volumes:
        - name: {{ .Values.elasticsearchSuperdesk.volumeName }}
          persistentVolumeClaim:
            claimName: elasticsearch-sd-persistent-volume-claim
      containers:
        - name: {{ .Values.elasticsearchSuperdesk.component }}
          image: "{{ .Values.elasticsearchSuperdesk.image }}:{{ .Values.elasticsearchSuperdesk.tag }}"
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
            requests:
              cpu: "4"
              memory: 8Gi
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: {{ .Values.elasticsearchSuperdesk.volumeName }}
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
