apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.memcached.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.memcached.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.memcached.component }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - lb
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - storage
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - database
      containers:
        - name: {{ .Values.memcached.name }}
          image: {{ .Values.memcached.image }}
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
            requests:
              cpu: "4"
              memory: 8Gi
          ports:
            - containerPort: 11211
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
