apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.mongodb.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.mongodb.component }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - lb
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - storage
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - database
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-persistent-volume-claim
      containers:
        - name: {{ .Values.mongodb.name }}
          image: "{{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}"
          resources:
            limits:
              cpu: "12"
              memory: 20Gi
            requests:
              cpu: "8"
              memory: 10Gi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
              subPath: mongodb
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
