apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      component: {{ .Values.nginx.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.nginx.component }}
      annotations:
        backup.velero.io/backup-volumes: {{ .Values.publisher.volumeName }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - lb
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - storage
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - database
      volumes:
        - name: {{ .Values.publisher.volumeName }}
          persistentVolumeClaim:
            claimName: publisher-persistent-volume-claim
      containers:
        - name: nginxpub
          image: "{{ .Values.nginx.image }}:{{ .Values.nginx.tag }}"
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
            requests:
              cpu: "4"
              memory: 8Gi
          ports:
            - containerPort: 80
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/www/publisher/public/uploads
              name: {{ .Values.publisher.volumeName }}
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5 && rm -f /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime"]
      imagePullSecrets:
        - name: harbor-access
