apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.rabbitmq.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.rabbitmq.component }}
      annotations:
        backup.velero.io/backup-volumes: {{ .Values.rabbitmq.volumeName }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - lb
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - storage
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - database
      volumes:
        - name: {{ .Values.rabbitmq.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.rabbitmq.volumeName }}
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image }}:{{ .Values.rabbitmq.tag }}"
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
            requests:
              cpu: "4"
              memory: 8Gi
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: {{ .Values.rabbitmq.volumeName }}
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
