apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.redis.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.redis.component }}
      annotations:
        backup.velero.io/backup-volumes: {{ .Values.redis.volumeName }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - lb
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - storage
            - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                - database
      volumes:
        - name: {{ .Values.redis.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.redis.volumeName }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
            requests:
              cpu: "4"
              memory: 8Gi
          ports:
            - containerPort: 6379
          volumeMounts:
          - mountPath: /data
            name: {{ .Values.redis.volumeName }}
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
