version: '2'
services:
  mongodb:
    image: mongo:3.4
    container_name: mongodb
    ports:
      - "27017:27017"
    #volumes:
    #  - /home/ubuntu/mongo_data:/data

  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - "6379:6379"

  elastic:
    image: elasticsearch:2
    container_name: elastic
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"


  superdesk:
    build:
      context: ../
      dockerfile: Dockerfile-test
    links:
      - mongodb
      - redis
      - elastic
    environment:
      - SUPERDESK_RELOAD=True
      - SUPERDESK_URL=http://localhost:5000/api
      - SUPERDESK_WS_URL=ws://localhost:5100
      - SUPERDESK_CLIENT_URL=http://localhost:9000
      - REDIS_URL=redis://redis:6379/1
      - MONGO_HOST=mongodb
    ports:
      - "5000:5000"
      - "5100:5100"
      - "5400:5400"
      - "9000:9000"
      - "35729:35729"
    volumes:
      - ../server:/opt/superdesk/
      - ../client-core:/opt/superdesk/client-core/
      - ./Procfile-dev:/opt/superdesk/Procfile
