mongodb:
  extends:
    file: common.yml
    service: mongodb
  ports:
    - "27017:27017"
  #volumes:
  #  - /home/ubuntu/mongo_data:/data

redis:
  extends:
    file: common.yml
    service: redis

elastic:
  extends:
    file: common.yml
    service: elastic
  ports:
    - "9200:9200"

superdesk:
  extends:
    file: common.yml
    service: superdesk
  links:
    - mongodb
    - redis
    - elastic
    - postfix
  environment:
    - SUPERDESK_RELOAD=True
    - SUPERDESK_URL=http://localhost:5000/api
    - SUPERDESK_WS_URL=ws://localhost:5100
    - SUPERDESK_CLIENT_URL=http://localhost:9000
  ports:
    - "5000:5000"
    - "5100:5100"
    - "5400:5400"
    - "9000:9000"
    - "35729:35729"
  volumes:
    - ../server:/opt/superdesk/
    - ../client:/opt/superdesk/client/
    - ../client-core:/opt/superdesk/client-core/
    - ./Procfile-dev:/opt/superdesk/Procfile
    - ./start-dev.sh:/opt/superdesk/start.sh
    - ./start-client.sh:/opt/superdesk/start-client.sh
